language: python
install:
  - pip install -r requirements.txt
script:
  - pytest
before_deploy:
  - npm install -g aws-cdk
  - cdk bootstrap
deploy:
  - provider: script
    skip_cleanup: true
    script:
      cdk deploy --require-approval never